### ISSUE TITLE
Finish Adding the FIRE implementation

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/pyre#3]
Add the ICRA2022 implementation for  the FIRE framework

**Comment by ChamzasKonstantinos** [comment]
A new implementation of pyre that includes ICRA2021/ICRA2022 and is fully in python will be added by the end of the summer

**Comment by jaychennn** [comment]
Hello, @ChamzasKonstantinos I hope this message finds you well. I was wondering if the FIRE framework (ICRA2022) has been implemented. I couldn’t find it in this repository, but I may have overlooked it. If possible, could you kindly confirm? Thank you in advance for your assistance.
